name: CI CD Pipeline

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  pre:
    name: pre
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Кэширование node_modules

      - name: Install dependencies
        run: npm ci | echo -e "\033[32mУстановка зависимостей...\033[0m"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules # Кэшируем npm-пакеты
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

  lint_test:
    runs-on: ubuntu-latest
    needs: pre
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

#      - name: Install dependencies
#        run: npm ci

      - name: eslint
        run: npm run lint:fix | echo -e "\033[32mЗапуск линтера\033[0m"

      - name: jest
        run: npm run test | echo -e "\033[32mЗапуск тестов\033[0m"

  build:
    runs-on: ubuntu-latest
    needs: lint_test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Build project
        run: npm run build | echo -e "\033[32mЗапуск сборки\033[0m"

      - name: Проверить содержимое папки dist
        run: ls -la .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ${{ github.workspace }}/dist